"""
Django settings for TestDjango project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
# django姜戈
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+h__eamr6bgp4_^2yfhx^=_043-p_$(0l-&j*bz3wdsh=srp*w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
	# 身份验证系统
    'django.contrib.auth',
	# 内容类型框架
    'django.contrib.contenttypes',
	# session框架
    'django.contrib.sessions',
	# 网站管理框架
    'django.contrib.sites',
	# 消息框架
    'django.contrib.messages',
	# 静态文件管理框架
    'django.contrib.staticfiles',
    'myApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TestDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TestDjango.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE'   : 'django.db.backends.postgresql_psycopg2',
	'ENGINE'   : 'django.db.backends.mysql',
	'ENGINE'   : 'django.db.backends.sqlite3',
	'ENGINE'   : 'django.db.backends.oracle',
	
        'NAME'     : 'sunck',
	连接数据库的用户名
        'USER'     : 'root',
	连接数据库的密码
        'PASSWORD' : 'weidi',
	连接数据库的主机地址.
	如果和数据库服务器是同一台物理机器,
	请将此处保留为空(或者设置为127.0.0.1,sqlite下不需要)
        'HOST'     : 'localhost',
        'PORT'     : '3306'
    }
}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
	如果使用sqlite,那么该数据库就是一个文件;
	在这种情况下,NAME将是一个完整的绝对路径,而且还
	包含该文件的名称.如果该文件不存在,它会在第一次同步数据库
	时自动创建.当指定路径时,总是使用正斜杠,即使是在Windows下
	(如:C:/homes/user/mysite/sqlite3.db)
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''

DATABASES = {
    'default': {
        'ENGINE'   : 'django.db.backends.mysql',
        'NAME'     : 'sunck',
        'USER'     : 'root',
        'PASSWORD' : 'weidi',
        'HOST'     : 'localhost',
        'PORT'     : '3306'
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

# 英文
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'

# 中文
LANGUAGE_CODE = 'zh-Hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
