# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('experience', models.TextField()),
                ('age', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.FloatField()),
                ('sex', models.BooleanField()),
                ('marry', models.NullBooleanField()),
                ('timeOfEntry', models.DateField(auto_now=True)),
                ('timeOfWork', models.TimeField()),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('idCard', models.FileField(upload_to='')),
                ('headPortrait', models.ImageField(upload_to='')),
            ],
        ),
    ]
