/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

#include "version.h"
const char *version_string = "1.19.5";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/root/mydev/tools/wget/etc/wgetrc\" -DLOCALEDIR=\"/root/mydev/tools/wget/share/locale\" -I. -I../lib -I../lib -I/usr/include/p11-kit-1 -DHAVE_LIBGNUTLS -DNDEBUG ";
const char *link_string = "gcc -I/usr/include/p11-kit-1 -DHAVE_LIBGNUTLS -DNDEBUG -lpcre -lnettle -lgnutls -lz ftp-opie.o gnutls.o http-ntlm.o ../lib/libgnu.a ";
